<?php
/**
 * Author: super
 * Date: 2020/11/13
 */

namespace app\admin\model;

use app\common\model\AdminCommon;

class Nav extends AdminCommon
{
    protected $pk = 'nav_id';

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    // 列表
    public function lists($data = [], $order = '', $size = 10)
    {
        $where = [];
        if (!$order) {
            $order = 'sort_num desc, ' . $this->pk . ' desc';
        }
        return $this->getListByWhere($where, $order, $size, $data);
    }

    // 修改一条数据
    public function updateOne($data)
    {
        $array = [
            'name' => $data['name'],
            'type' => $data['type'],
            'pic' => $data['pic'],
            'link' => $data['link'],
            'sort_num' => $data['sort_num'] ? $data['sort_num'] : 10,
        ];

        return $this->updateOneByID($data[$this->pk], $array);
    }

    // 新增一条数据
    public function insertRow($data)
    {
        $array = [
            'name' => $data['name'],
            'type' => $data['type'],
            'pic' => $data['pic'],
            'link' => $data['link'],
            'sort_num' => $data['sort_num'] ? $data['sort_num'] : 10,
            'status' => $data['status'] ?? 2
        ];

        return $this->insertOne($array);
    }

}