<?php

namespace app\admin\controller;

use app\admin\model\Nav as Model;

class Nav extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $data = Model::mark()->lists(input());

        $this->assign('list', $data);
        $this->assign('page', $data->render());

        return $this->fetch();
    }

    // 修改/新增数据
    public function update()
    {
        if (request()->isAjax()) {
            $id = input('id/d', '');
            if ($id) {
                $result = Model::mark()->updateOne(input());
                return $result !== false ? ['code' => 200, 'msg' => '修改成功'] : ['code' => 500, 'msg' => '修改失败，网络繁忙'];
            } else {
                $result = Model::mark()->insertRow(input());
                return $result ? ['code' => 200, 'msg' => '添加成功'] : ['code' => 500, 'msg' => '添加失败，网络繁忙'];
            }
        }

        $id = input('id/d');
        $data = Model::mark()->getOneByID($id);
        $this->assign('data', $data);

        return $this->fetch();
    }

    // 删除一条数据
    public function delete()
    {
        $id = input('id/d');

        $result = Model::mark()->deleteOneByID($id, 'pic');
        return $result ? ['code' => 200, 'msg' => '删除成功'] : ['code' => 500, 'msg' => '删除失败，网络繁忙'];
    }

    // 修改状态
    public function status()
    {
        $id = input('id/d');
        $status = input('status/d');

        $result = Model::mark()->updateOneByID($id, ['status' => $status]);
        return $result ? ['code' => 200, 'msg' => '修改成功'] : ['code' => 500, 'msg' => '修改失败，网络繁忙'];
    }
}
