<?php
/**
 * Author: super
 * Date: 2020/11/13
 */

namespace app\common\model;

use think\exception\DbException;

class AdminCommon extends Common
{
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * get list by where
     * @access public
     * @param array $where 条件数组
     * @param string $order 排序
     * @param int $size 分页每页数量
     * @param array $query 分页参数
     * @return mixed
     */
    public function getListByWhere($where = [], $order = '', $size = 10, $query = [])
    {
        try {
            return $this->where($where)->order($order)->paginate($size, false, ['query' => $query]);
        } catch (DbException $e) {
            Error::mark()->writeError('AdminCommon/getListByWhere', $e->getMessage());
            return [];
        }
    }

}