<?php
/**
 * Author: super
 * Date: 2020/11/13
 */

namespace app\common\model;

class Error extends Common
{
    public $pk = 'error_id';

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * return new static
     * @return static
     */
    public static function mark()
    {
        return new static();
    }

    /**
     * write error
     * @access public
     * @param string $where 报错位置
     * @param mixed $text 报错详情
     * @return int|mixed|string
     */
    public function writeError(string $where, $text)
    {
        if (!is_string($text)) {
            $text = json_encode($text, JSON_UNESCAPED_UNICODE);
        }
        $error = $where . ' ---> ' . $text;
        $exist = $this->getOneByWhere([['text', '=', $error]]);
        if ($exist) {
            return $this->updateOneByID($exist[$this->pk], ['last_time' => time()]);
        } else {
            return $this->insertOne(['text' => $text, 'time' => time(), 'last_time' => time()]);
        }
    }

}