<?php
/**
 * Author: super
 * Date: 2020/11/13
 */

namespace app\common\model;

class IndexCommon extends Common
{
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * return new static
     * @return static
     */
    public static function mark()
    {
        return new static();
    }

    public function getListByWhere($where)
    {


    }

}